config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
  resources :posts do 
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    validates :user_id, presence: true
    validates :image, presence: true
    
    has_attached_file :image, styles: { :medium => "640x" }
    # validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
    validates_attachment :image,
    content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
    
    belongs_to :user
    has_many :comments, dependent: :destroy
    
    validates :caption, presence: true, length: {maximum: 300, minimum: 3}
    
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :user_name, presence: true, length: { minimum: 3, maximum: 16 }
  
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_post
    
    def create
        @comment = @post.comments.build(comment_params)
        @comment.user_id = current_user.id
        
        if @comment.save
            respond_to do |format|
                format.html {redirect_to root_path}
                format.js
            end
        else
           flash[:danger] = "Check the comment form, something went horribly worng."
           render root_path
        end
    end
    
    def destroy
        # find the post comment
        @comment = @post.comments.find(params[:id])
        
        if @comment.user_id == current_user.id
            @comment.destroy
            respond_to do |format|
               format.html {redirect_to root_path}
               format.js
            end
        end
    end
    
    private
    
    def comment_params
       params.require(:comment).permit(:content) 
    end
    
    def set_post
        @post = Post.find(params[:post_id])
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :index]
    before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :owned_post, only: [:edit, :update, :destroy]
    
    def index
        @posts = Post.all
        @comment = Comment.new
    end
    
    def new
        @post = Post.new
    end
    
    def create
        @post = current_user.posts.create(post_params)
        if @post.save
            flash[:success] = "Your post has been created!"
            redirect_to posts_path
        else
            flash[:alert] = "Your new post couldn't be created! Please check the form."
            render "new"
       end
    end
    
    def show
        @comment = Comment.new
    end
    
    
    def edit
        # # version 1 to prevent other users from editing
        # if current_user.id != @post.user_id
        #     flash[:danger] = "You are not allowed to do that"
        #     redirect_to root_path
        # end
    end
    
    def update
       if @post.save
           flash[:success] = "Post updated."
           @post.update(post_params)
           redirect_to post_path(@post)
       else
           flash.now[:alert] = "Update failed. Please check the form."
           render :edit
       end
    end
    
    def destroy
       @post.destroy
       redirect_to posts_path
    end
    
    
    private
    def set_post
       @post = Post.find(params[:id]) 
    end
    
    def post_params
        params.require(:post).permit(:image, :caption)
    end
    
    def owned_post
        if current_user != @post.user
            flash[:danger] = "That post doesn't belong to you!"
            redirect_to root_path
        end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
   private
   
   def sign_up_params
      params.require(:user).permit(:email, :user_name, :password, :password_confirmation) 
   end
   
   def account_update_params
      params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password) 
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def alert_for(flash_type)
        {
            success: 'alert-success',
            error: "alert-danger",
            alert: "alert-warning",
            notice: 'alert-info'
        }[flash_type.to_sym] || flash_type.to_s
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
# comment
<div class="user-name">
    <%= comment.user.user_name %>
</div>
<div class="comment-content">
    <%= comment.content %>
</div>
<% if comment.user == current_user %>
    <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" }, remote: true do %>
        <span class= "glyphicon glyphicon-remove delete-comment"></span>
    <% end %>
<% end %>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$("#comments_<%= @post.id %>").html("<%= j render @post.comments, post: @post, comment: @comment %>");

app/views/layouts/_flash_messages.html.erb
<div class="container">
    <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name %>">
            <%= msg %>
        </div>
    <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "kjdesigns", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
     
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "New Post", new_post_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= render "layouts/flash_messages" %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form-wrapper">

<%= simple_form_for @post, html: {class: "form-horizontal", multipart: true} do |f| %>
    <%= f.input :image, class: "form-group text-center" %>
    <%= f.input :caption, class: "form-group text-center" %>
    <%= f.button :submit, class: "btn btn-success" %>
<% end %>

    
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
    <div class="posts">
        <div class="post-head">
            <div class="thumb-img">
                
            </div>
            <div class="user-name">
                <%= post.user.user_name %>
            </div>
            <div class="time-ago">
                <%= time_ago_in_words(post.created_at) %>
            </div>
        </div>
        <div class="image center-block">
            <%= link_to (image_tag post.image.url(:medium), class: "img-responsive"), post_path(post) %>
            
        </div>
        <div class="post-bottom">
            <div class="caption">
                <div class="caption-content">
                    <div class="user-name">
                        <%= post.user.user_name %>
                    </div>
                    <%= post.caption %>
                </div>
                <div class="comments" id="comments_<%=post.id%>">
                     <% if post.comments %>
                        <%= render post.comments, post: post %>
                    <% end %>
                </div>
            </div>
           
        </div>
        <div class="comment-like-form row">
            <div class="like-button col-sm-1">
                <span class="glyphicon glyphicon-heart-empty"></span>
            </div>
            <div class="comment-form col-sm-11">
                <%= form_for([post, post.comments.build], remote: true) do |f| %>
                    <%= f.text_field :content, placeholder: "Add a comment...", class: "comment_content", id: "comment_content_#{post.id}" %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/posts/edit.html.erb
<div class="text-center">
    <%= image_tag @post.image.url(:medium) %>
</div>


<%= render "form" %>

<div class="text-center">
    <%= link_to "Delete Post", post_path(@post), method: :delete, data: {confirm: "Are you sure you want to delete this post?" } %> 
     |
    <%= link_to "Cancel", posts_path %> 
</div>

app/views/posts/index.html.erb
<h1>Photogram</h1>

<% @posts.each do |post| %>
    <%= render "post", post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render "form" %>
<div class="text-center">
    <%= link_to "Cancel", root_path %>
</div>

app/views/posts/show.html.erb
<<<<<<< HEAD
<div class="posts-wrapper row">
    <div class="post">
        <div class="post-head">
            <div class="name">
                ken banico
            </div>
        </div>
        <div class="image center-block">
            <%= image_tag @post.image.url(:medium), class: "img-responsive" %>
        </div>
        <p class="caption">
            <p><%= @post.caption %></p>
           
        </p>
        
        <div class="text-center edit-links">
            <% if current_user.id == @post.user_id %>
                <%= link_to "Cancel", posts_path %> |
                <%= link_to "Edit Post", edit_post_path(@post) %>
            <% else %>
                 <%= link_to "Cancel", posts_path %>
            <% end %>
        </div>
       
    </div>
</div>
=======
<%= render "post", post: @post %>
    <% if @post.user.id == current_user.id %>
        <div class="text-center edit-links">
            <%= link_to "Cancel", posts_path %> 
            |
            <%= link_to "Edit Post", edit_post_path(@post) %>
        </div>
    <% else %>
        <div class="text-center edit-links">
            <%= link_to "Cancel", posts_path %>
        </div>
    <% end %>
>>>>>>> add_comments